config/routes.rb
Rails.application.routes.draw do
  get 'blogs' => 'blog#index', as: 'blogs'
  get 'blogs/new' => 'blog#new', as: 'new_blog'
  get 'blogs/:id/edit' => 'blog#edit', as: 'edit_blog'
  get 'blogs/:id' => 'blog#show', as: 'blog'
  post 'blogs' => 'blog#create'
  delete 'blogs/:id' => 'blog#destroy'
  patch 'blogs/:id' => 'blog#update'
  root 'blog#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, :content, presence: true
    validates :title, uniqueness: true
    validates :title, length: { minimum: 4 }
    validates :content, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end 

  def new 
    @blog = Blog.new
  end 

  def create 
    @blog = Blog.create(blog_params)
    if @blog.valid?
      redirect_to blogs_path
    end 
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end 
  
  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
    redirect_to blogs_path
    end
  end

  private 
  def blog_params
    params.require(:blog).permit(:title, :content)
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<h2>Edit Blog Post</h2>

<%= form_with model: @blog, url: blog_path(@blog), method: :patch, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <br />
  <%= form.label :content %>
  <%= form.text_field :content %>
  <br /> 
  <%= form.submit %>
  <% end %>
  <br />

  <p>Back to <%= link_to 'Blog Content', blog_path %></p>

app/views/blog/index.html.erb
<h1>Blog Post</h1>
<img id="myimage" src="https://w0.peakpx.com/wallpaper/591/880/HD-wallpaper-ryomen-sukuna-jujutsu-kaisen-thumbnail.jpg" alt="JJK"></img>
<ul id= "list"
  <% @blogs.each do |blog| %>
    <li><%= link_to blog.title, blog_path(blog) %></li>
    <% end %>
</ul>
<br />
<%=link_to 'Add a new blog', new_blog_path %>

app/views/blog/new.html.erb
<h3>Write a new Blog</h3>
<%= form_with model: @blog do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <br />
  <%= form.label :content %>
  <%= form.text_field :content %>
  <br /> 
  <%= form.submit %>
  <% end %>
  <br />

  <p>Back to <%= link_to 'Blog List', blogs_path %></p>

app/views/blog/show.html.erb
<h3><%= @blog.title %></h3>

<p>Content: <%= @blog.content %></p>
<br />
<p><%= link_to 'Edit', edit_blog_path(@blog) %></p>
<p><%= button_to 'Delete', blog_path(@blog), method: :delete %> </p>

<p>Back to <%= link_to 'Blog List', blogs_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>